name: urban-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=17
  - pip
  - pip:
      - pyspark
      - delta-spark
      - requests
      - pandas
      - pytest
      - prefect
